# -*- coding: utf-8 -*-
"""AME-MDsimulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FhsBmLoPhOrvg2-DzLpBj4JRzyzR05Lo

#### **👋 Welcome to this Molecular Dynamics (MD) Biophysical Simulation Colab Notebook!** 🎉

This jupyter notebook contains the complete code for the MD simulation and computational modeling study for β-sesquiphellandrene and TLR4/MD-2 complex as part of the research study on .

This notebook is designed to guide anyone through the steps of setting up and running the **Molecular Dynamics simulation** for the **Ligand-Protein Interaction of the TLR4-MD2 complex with β-sesquiphellandrene**. 🧪✨

**What you'll find here:**

1.  **GROMACS Installation & Setup:** We start by compiling and installing GROMACS from source, optimized for GPU performance. This ensures you have the robust tools needed for high-performance simulations. CUDA acceleration is configured to make the most of Colab's powerful GPUs! 🛠️💻

2.  **Force Field Integration:** We integrate the CHARMM36 force field for both the protein and the ligand. The CHARMM36 force field is widely used for biological systems, providing accurate parameters for molecular interactions. We also handle the preparation of ligand topology using CgenFF outputs.

3.  **System Preparation:** This involves several crucial steps:
    *   **Protein Processing:** Using `pdb2gmx` to prepare your protein structure and generate its topology.
    *   **Ligand Topology:** Converting CgenFF outputs (.str, .mol2) into GROMACS-compatible `.itp` and `.prm` files.
    *   **Complex Formation:** Merging the protein and ligand structures into a single complex, followed by centering and creating a periodic boundary box.
    *   **Solvation & Ionization:** Hydrating your system with water molecules and neutralizing it with ions to mimic physiological conditions.

4.  **MD Simulation Stages:** Once the system is prepared, we proceed with the simulation pipeline:
    *   **Energy Minimization (EM):** Relaxing the system to remove unfavorable contacts and steric clashes.
    *   **NVT Equilibration:** Bringing the system to the desired temperature under constant volume.
    *   **NPT Equilibration:** Adjusting the system to the target pressure and density under constant temperature.
    *   **Production MD:** Running the main simulation to collect data for analysis.

5.  **Checkpointing & Resumption:** This notebook is configured for robustness! Simulations are set up with frequent checkpointing, allowing you to seamlessly resume your run from the last saved state. This is especially useful for long simulations on Colab, enabling you to continue even if your session disconnects. Simply install GROMACS and jump back into the simulation code block!

**NB:** ⚠️ Upon completion of all requisite pre-simulation calculations, methodological steps, and file generation, the molecular dynamics (MD) simulation code block section can be executed autonomously, independent of preceding code blocks. For example, in a scenario where a simulation has been initiated with checkpointing activated, subsequent resumption only requires the installation of GROMACS and CHARMM36, followed by direct invocation of the relevant simulation code block to continue from the last saved state.

**Ready to dive deep in!**

---
"""

# import drive and content

from google.colab import drive
drive.mount('/content/drive')

# check contents
!ls /content

"""**INSTALLING GROMACS WITH CUDA**"""

# Update package list
!apt update -qq
# Install necessary build tools and libraries
!apt install -y build-essential cmake pkg-config git wget
!apt install -y libfftw3-dev libopenmpi-dev

# Commented out IPython magic to ensure Python compatibility.
# download gromacs source code
GROMACS_VERSION = "2025.2" # Make sure this matches the version you want!
GROMACS_FILE = f"gromacs-{GROMACS_VERSION}.tar.gz"
GROMACS_URL="https://ftp.gromacs.org/gromacs/gromacs-2025.2.tar.gz"


# Navigate to /content (where downloads usually land)
# %cd /content

# Clean up any previous failed downloads or directories from prior attempts
!rm -f index.html {GROMACS_FILE}
!rm -rf gromacs-{GROMACS_VERSION}

# Download the correct GROMACS source tarball
print(f"Downloading {GROMACS_FILE} from {GROMACS_URL}...")
!wget {GROMACS_URL}

print("\nDownload complete. Check the output above for 'saved'.")

# Commented out IPython magic to ensure Python compatibility.
# Extraction step

# Ensure variables are set for this cell, if running independently or after a runtime restart
GROMACS_VERSION = "2025.2" # IMPORTANT: Must match the version downloaded in the previous step!
GROMACS_FILE = f"gromacs-{GROMACS_VERSION}.tar.gz"

# Ensure we are in the /content directory where the tarball was downloaded
# %cd /content

# Clean up any pre-existing extracted GROMACS directory to avoid conflicts
!rm -rf gromacs-{GROMACS_VERSION}

# Extract the GROMACS source tarball
print(f"Extracting {GROMACS_FILE}...")
!tar xfz {GROMACS_FILE}
print("Extraction complete.")

# Change into the extracted GROMACS source directory
print(f"Navigating to gromacs-{GROMACS_VERSION}...")
# %cd gromacs-{GROMACS_VERSION}

# Create a build directory (standard practice for out-of-source builds)
print("Creating build directory...")
!mkdir build

# Change into the build directory
print("Navigating to build directory...")
# %cd build

# Verify current path - should be /content/gromacs-2025.2/build
print("\nCurrent working directory:")
!pwd

# configure with cmake
!cmake .. \
    -DGMX_BUILD_OWN_FFTW=ON \
    -DREGRESSIONTEST_DOWNLOAD=OFF \
    -DGMX_GPU=CUDA \
    -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda \
    -DGMX_FFT_LIBRARY=fftw3 \
    -DCMAKE_INSTALL_PREFIX=/usr/local/gromacs \
    -DSHARED_LIBS=ON \
    -DGMX_HWLOC=OFF \
    -DGMX_MPI=OFF

# compile gromacs
!make -j$(nproc)

!make install

import os
os.environ['PATH'] += ':/usr/local/gromacs/bin'

!gmx --version

"""**INSTALLING CHARMM36 FORCEFIELD**"""

''' We downloaded the charmm36 forcefield from makerell lab for our simulation, because it isn't included in our gromacs by default
and it is the specific forcefield used for ligand topology from CgenFF. For consistency, we will use it for protein topology '''

# We first download and upload charmm36-jul2022.ff.tar.gz (or .zip) to drive

print("Extracting charmm36-jul2022.ff (MacKerell Lab version)...")
# Adjust filename if it's .zip or .tgz
!tar -xzf /content/drive/MyDrive/charmm36-jul2022.ff.tgz -C /content/ # file is .tgz
print("Extraction complete.")

# We move extracted charmm36 file to the right gromacs directory on colab

# The extracted directory will be in the current working directory, which is /content
SOURCE_FF_DIR="/content/charmm36-jul2022.ff"
GROMACS_FF_DEST="/usr/local/gromacs/share/gromacs/top/"

print(f"Moving {SOURCE_FF_DIR} to {GROMACS_FF_DEST}...")
!sudo mv {SOURCE_FF_DIR} {GROMACS_FF_DEST}
print(f"Moved charmm36-jul2022.ff to GROMACS force field directory.")

print("\nNow, we run pdb2gmx interactively to find the number for charmm36-jul2022.ff. This is crucial for the protein.")

"""**PROCESSING OUR PROTEIN TO OBTAIN TOPOLOGY (.top) AND GROMACS (.gro) PARAMETERS USING PDB2GMX WITH CHARMM36 FORCEFIELD**"""

''' We process our protein to obtain the .gro and .top files using our CHARMM36 force field '''

# Define the protein-only PDB file
PROTEIN_PDB="/content/drive/MyDrive/3vq2_protein_clean.pdb"

# Define output paths for .gro and .top files to save in Drive
OUTPUT_DIR="/content/drive/MyDrive"
PROTEIN_GRO=f"{OUTPUT_DIR}/protein_processed.gro"
TOPOL_TOP=f"{OUTPUT_DIR}/topol.top"

print("Running pdb2gmx to list available force fields (interactive mode)...")
print("Look for a CHARMM or your desired force field in the list, note and input its number.")

# Run pdb2gmx
# -f: input PDB file
# -o: output .gro file (GROMACS coordinate format)
# -p: output topology file for the entire system (this will be the main topol.top)
# -ff: force field selection (charmm36-jul2022 is a common CHARMM36 version)
# -water: water model (tip3p is common with CHARMM36)
# -ignh: ignore hydrogens in input (pdb2gmx will add its own based on FF)

# It will prompt you to select a force field from a list. Look for your desired force field. Mine is charmm27 since it doesn't have charmm36 latest
!gmx pdb2gmx -f {PROTEIN_PDB} -o {PROTEIN_GRO} -p {TOPOL_TOP} -water tip3p -ignh

# Alternatively use this code below and replace '8' for your selected force field.
# !echo 8 | gmx pdb2gmx -f {PROTEIN_ONLY_PDB} -o {PROTEIN_GRO} -p {TOPOL_TOP} -water tip3p -ignh

"""**THIS CODE SECTION IS UNNECESSARY IF EVERYTHING RUNS WELL. THIS SECTION ONLY CHECKS IF CHARMM36 WAS PROPERLY INSTALLED IN GROMACS DIRECTORY**"""

# Commented out IPython magic to ensure Python compatibility.
# Navigate to the GROMACS force field directory
# %cd /usr/local/gromacs/share/gromacs/top/

# List the contents of the directory to see if charmm36-jul2022.ff is there
print("\nContents of GROMACS force field directory:")
!ls -F

# If charmm36-jul2022.ff is listed above, then list its contents
print("\nContents of charmm36-jul2022.ff (if it exists):")
!ls -F charmm36-jul2022.ff/

# # Navigate to the installed charmm36-jul2022.ff directory
# %cd /usr/local/gromacs/share/gromacs/top/charmm36-jul2022.ff/

# # Display the contents of forcefield.itp to see the name assigned to charmm36
# print("\nContents of forcefield.itp:")
# !cat forcefield.itp | head -n 10 # Display first 10 lines

"""####Note:
1. Protein is obtained from RCSB
2. Ligand is obtained from PubChem
3. Protein .gro and .top is processed with the CHARMM36 forcefield.
4. Ligand topology will be generated from CgenFF
5. Ligand topology .top will be converted to include .itp file, and inspected. System definitions will be removed such as water molecules etc, since this should only be defined in the protein .top.
6. Protein .gro and Ligand PDB are combined into a complex system.
7. Protein .top and Ligand .itp files are integrated to have a single topology file for grompp gromacs.


"""

''' In this code block, we process the .str file using the cgenff_charmm2
python script file downloaded from Lemkul lab and uploaded into my drive.
We should generate a .itp .top .prm and .pdb files '''

import os
import shutil
import subprocess
import sys

# --- 1. CONFIGURATION ---
BASE_DIR = "/content/drive/MyDrive"
SCRIPT_PATH = f"{BASE_DIR}/cgenff_charmm2gmx.py"
STR_PATH    = f"{BASE_DIR}/519764.str"
MOL2_PATH   = f"{BASE_DIR}/519764.mol2"
FF_DIR      = "/usr/local/gromacs/share/gromacs/top/charmm36-jul2022.ff"
RESNAME     = "519764"

# --- 2. CREATE THE MOL2 FILE ---
'''
We created the mol2 here instead of uploading to drive because of Line Endings.
Sometimes files uploaded from Windows to Linux (Colab) have hidden
"carriage return" characters (\r\n) that can cause old scripts to crash.
Writing it fresh in Python guarantees it is "clean" for Linux environment (Colab).
'''
# We write the mol2 content copied from the mol2 file found in cgenff zip file
mol2_content = """@<TRIPOS>MOLECULE
519764
39 39 0 0 0
SMALL
USER_CHARGES
@<TRIPOS>ATOM
1 C1 -26.7790 -18.1020 32.2550 C.3 1 UNK1 -0.0910
2 C2 -28.0110 -17.1810 32.2860 C.3 1 UNK1 -0.2660
3 C3 -26.9560 -19.2290 31.1830 C.3 1 UNK1 0.1470
4 C4 -26.1380 -20.5170 31.5180 C.3 1 UNK1 -0.2460
5 C5 -26.4890 -21.6400 30.5540 C.3 1 UNK1 -0.2910
6 C6 -27.9660 -21.9260 30.6860 C.2 1 UNK1 0.3700
7 C7 -28.8980 -20.7770 30.7580 C.2 1 UNK1 -0.1440
8 C8 -28.4270 -23.1820 30.7240 C.2 1 UNK1 -0.6820
9 C9 -28.4360 -19.5300 30.9540 C.2 1 UNK1 -0.3220
10 C10 -25.4560 -17.3040 32.0600 C.3 1 UNK1 -0.1990
11 C11 -24.8780 -17.3090 30.6360 C.3 1 UNK1 -0.1610
12 C12 -23.4760 -17.8750 30.6000 C.2 1 UNK1 -0.1490
13 C13 -22.3470 -17.2500 31.0280 C.2 1 UNK1 -0.0020
14 C14 -21.0290 -17.9730 30.9190 C.3 1 UNK1 -0.2720
15 C15 -22.3030 -15.8520 31.6060 C.3 1 UNK1 -0.2720
16 H1 -26.7189 -18.5906 33.2275 H 1 UNK1 0.0900
17 H2 -28.9104 -17.7810 32.4238 H 1 UNK1 0.0900
18 H3 -28.0802 -16.6341 31.3456 H 1 UNK1 0.0900
19 H4 -27.9164 -16.4744 33.1106 H 1 UNK1 0.0900
20 H5 -26.5627 -18.8386 30.2444 H 1 UNK1 0.0900
21 H6 -25.0736 -20.2961 31.4381 H 1 UNK1 0.0900
22 H7 -26.3686 -20.8332 32.5353 H 1 UNK1 0.0900
23 H8 -26.2616 -21.3348 29.5326 H 1 UNK1 0.0900
24 H9 -25.9160 -22.5332 30.8029 H 1 UNK1 0.0900
25 H10 -29.9697 -20.9444 30.6509 H 1 UNK1 0.1500
26 H11 -27.7325 -24.0196 30.6593 H 1 UNK1 0.2100
27 H12 -29.4969 -23.3672 30.8197 H 1 UNK1 0.2100
28 H13 -29.1446 -18.7018 30.9494 H 1 UNK1 0.1500
29 H14 -25.6456 -16.2679 32.3406 H 1 UNK1 0.0900
30 H15 -24.7066 -17.7303 32.7269 H 1 UNK1 0.0900
31 H16 -25.5197 -17.9159 29.9972 H 1 UNK1 0.0900
32 H17 -24.8548 -16.2857 30.2614 H 1 UNK1 0.0900
33 H18 -23.3597 -18.8792 30.1923 H 1 UNK1 0.1500
34 H19 -20.2320 -17.3364 31.3030 H 1 UNK1 0.0900
35 H20 -20.8306 -18.2123 29.8742 H 1 UNK1 0.0900
36 H21 -21.0700 -18.8939 31.5008 H 1 UNK1 0.0900
37 H22 -21.2756 -15.5983 31.8668 H 1 UNK1 0.0900
38 H23 -22.9255 -15.8080 32.4997 H 1 UNK1 0.0900
39 H24 -22.6762 -15.1414 30.8684 H 1 UNK1 0.0900
@<TRIPOS>BOND
1 1 2 1
2 1 10 1
3 1 3 1
4 3 9 1
5 3 4 1
6 4 5 1
7 5 6 1
8 6 7 1
9 6 8 2
10 7 9 2
11 10 11 1
12 11 12 1
13 12 13 2
14 13 15 1
15 13 14 1
16 1 16 1
17 2 17 1
18 2 18 1
19 2 19 1
20 3 20 1
21 4 21 1
22 4 22 1
23 5 23 1
24 5 24 1
25 7 25 1
26 8 26 1
27 8 27 1
28 9 28 1
29 10 29 1
30 10 30 1
31 11 31 1
32 11 32 1
33 12 33 1
34 14 34 1
35 14 35 1
36 14 36 1
37 15 37 1
38 15 38 1
39 15 39 1
"""
with open(MOL2_PATH, "w") as f:
    f.write(mol2_content)
print(f"✅ Created {MOL2_PATH} from inspection data.")

# --- 3. FIX DEPENDENCIES ---
print("🔧 Ensuring Dependencies (NumPy < 2.0, NetworkX 2.5)...")
subprocess.check_call([sys.executable, "-m", "pip", "install", "numpy<2.0", "networkx==2.5"])

# --- 4. RUN CONVERSION ---
print(f"🚀 Running CGenFF to GROMACS conversion for {RESNAME}...")
os.chdir(BASE_DIR)

# Syntax: python script.py [RESNAME] [MOL2_FILE] [STR_FILE] [FF_DIR]
cmd = [sys.executable, SCRIPT_PATH, RESNAME, MOL2_PATH, STR_PATH, FF_DIR]

try:
    result = subprocess.run(cmd, capture_output=True, text=True)

    # --- 5. PROCESS OUTPUTS ---
    if os.path.exists("519764.prm"):
        print("\n🎉 SUCCESS! Conversion Finished.")

        # A) Rename Parameters (The Muscle)
        print("   -> Renaming 519764.prm to 519_ffbonded.itp")
        shutil.move("519764.prm", "519_ffbonded.itp")

        # B) Fix Topology Name (The Skeleton)
        if os.path.exists("519764.itp"):
            print("   -> Creating 519.itp (with corrected name '519')...")
            with open("519764.itp", "r") as f:
                content = f.read()
            content = content.replace("519764", "519")
            with open("519.itp", "w") as f:
                f.write(content)

        # C) Check PDB
        if os.path.exists("519764_ini.pdb"):
            print("   -> GENERATED: 519764_ini.pdb")
            print("      (⚠️ IMPORTANT: We merge this PDB with our protein .gro!)")

    else:
        print("\n❌ Script ran but failed to generate output.")
        print("--- ERROR LOG ---")
        print(result.stdout)
        print(result.stderr)

except Exception as e:
    print(f"❌ Execution failed: {e}")

"""**INTEGRATING CGENFF PROCESSED LIGAND .ITP INTO PROTEIN (MASTER) TOPOLOGY**"""

''' Integrating our Ligand include-Topology into the Master Topology generated from Protein by pdb2gmx '''

# --- CONFIGURATION ---
OUTPUT_DIR = "/content/drive/MyDrive"
TOPOL_TOP = f"{OUTPUT_DIR}/topol.top"
LIGAND_ITP_FINAL = "519.itp"      # The clean file we just generated
LIGAND_RESIDUE_NAME = "519"       # Matches [ moleculetype ] in 519.itp

# --- CRITICAL: DEFINE PROTEIN CHAINS ---
# Since we have full TLR4-MD2 complex, pdb2gmx likely generated two chains representing two proteins.
# Check directory for "topol_Protein_chain_A.itp" and "topol_Protein_chain_C.itp" generated from protein processing
# Then, we list BOTH here.
PROTEIN_MOLECULES = [
    ("Protein_chain_A", 1),
    ("Protein_chain_C", 1)  # Assuming Chain C is MD2 (Standard for 3VQ2)
]

print(f"Rewriting {TOPOL_TOP}...")

# 1. Read existing topology
with open(TOPOL_TOP, "r") as f:
    lines = f.readlines()

# 2. Preserve Header (Everything before [ molecules ])
new_lines = []
found_molecules = False

# We also check if the parameter file (muscle) is already included
has_ffbonded = False
ffbonded_include = '#include "519_ffbonded.itp"\n'

for line in lines:
    if "519_ffbonded.itp" in line:
        has_ffbonded = True

    if '[ molecules ]' in line:
        found_molecules = True
        continue # Stop reading old molecule list

    if not found_molecules:
        new_lines.append(line)

# 3. Ensure 519_ffbonded.itp is included at the TOP
# It must be after the forcefield include
if not has_ffbonded:
    print("   -> Injecting missing parameter file (519_ffbonded.itp) into header...")
    # Find index of forcefield include
    insert_idx = 0
    for i, line in enumerate(new_lines):
        if "forcefield.itp" in line:
            insert_idx = i + 1
            break
    new_lines.insert(insert_idx, ffbonded_include)

# 4. Write New Topology
with open(TOPOL_TOP, "w") as f:
    # A) Write the preserved header
    f.writelines(new_lines)

    # B) Add Ligand Topology Include (The Skeleton)
    f.write(f'\n; Include Ligand Topology\n')
    f.write(f'#include "{LIGAND_ITP_FINAL}"\n')

    # C) Write Consolidated [ molecules ] Section
    f.write(f'\n[ molecules ]\n')
    f.write(f'; Compound        #mols\n')

    # Write Protein Chains
    for name, count in PROTEIN_MOLECULES:
        f.write(f'{name:<15} {count}\n')

    # Write Ligand
    f.write(f'{LIGAND_RESIDUE_NAME:<15} 1\n')

print("✅ Topology updated successfully!")
print(f"   -> Ligand Name: {LIGAND_RESIDUE_NAME}")
print(f"   -> Protein Chains: {[x[0] for x in PROTEIN_MOLECULES]}")

# Verify
print(f"\nLast 20 lines of {TOPOL_TOP}:")
!tail -n 20 {TOPOL_TOP}

"""**MERGING OUR PROTEIN .GRO WITH CGENFF PROCESSED LIGAND .PDB TO CREATE A SINGLE UNIT COMPLEX SYSTEM**"""

import os
import shutil

'''
We merge our protein .gro and ligand pdb to have a single complex.gro system.
Then we calculate the cubic box size and center the system.
'''

# --- CONFIGURATION ---
BASE_DIR = "/content/drive/MyDrive"
PROTEIN_GRO = f"{BASE_DIR}/protein_processed.gro"   # From pdb2gmx
LIGAND_PDB  = f"{BASE_DIR}/519764_ini.pdb"         # From cgenff conversion output
COMPLEX_RAW = f"{BASE_DIR}/complex_raw.gro"        # Intermediate (merged but not centered)
COMPLEX_FIN = f"{BASE_DIR}/complex.gro"            # Final (merged + centered + boxed)

print("🚀 Starting Coordinate Merge & Box Setup...")

# 1. Convert NEW Ligand PDB to GRO format
# We use a temporary name. We DO NOT use -center here.
ligand_tmp = "ligand_tmp.gro"
cmd_conv = f"gmx editconf -f {LIGAND_PDB} -o {ligand_tmp}"
os.system(cmd_conv)

# 2. Read Files
if not os.path.exists(PROTEIN_GRO) or not os.path.exists(ligand_tmp):
    print("❌ Error: Missing input files. Check protein_processed.gro or 519764_ini.pdb")
else:
    with open(PROTEIN_GRO, 'r') as f:
        prot_lines = f.readlines()
    with open(ligand_tmp, 'r') as f:
        lig_lines = f.readlines()

    # 3. Parse Data (Strip Headers/Footers)
    # Protein
    prot_atom_count = int(prot_lines[1].strip())
    prot_atoms = prot_lines[2:-1]  # Keep atoms, drop box line

    # Ligand
    lig_atom_count = int(lig_lines[1].strip())
    lig_atoms = lig_lines[2:-1]    # Keep atoms, drop box line

    # 4. Create Raw Complex
    total_atoms = prot_atom_count + lig_atom_count
    print(f"   Merging: {prot_atom_count} Protein Atoms + {lig_atom_count} Ligand Atoms")

    with open(COMPLEX_RAW, 'w') as f:
        f.write("TLR4-MD2-Ligand Raw Merge\n")
        f.write(f"{total_atoms}\n")
        f.writelines(prot_atoms)
        f.writelines(lig_atoms)
        # We write a dummy box line just to make the format valid for the next step
        f.write("   10.00000   10.00000   10.00000\n")

    # 5. Apply the "Box and Center" Logic (The user's requirement)
    # We use gmx editconf on the COMBINED file.
    # -c: Center the complex
    # -d 1.0: Add 1.0 nm buffer (standard)
    # -bt cubic: Cubic box
    print("\n📦 Calculating Cubic Box & Centering Coordinates...")
    cmd_box = f"gmx editconf -f {COMPLEX_RAW} -o {COMPLEX_FIN} -c -d 1.0 -bt cubic"

    exit_code = os.system(cmd_box)

    if exit_code == 0:
        print("\n✅ SUCCESS!")
        print(f"   Final Structure: {COMPLEX_FIN}")
        print("   (This file is now Merged, Centered, and Boxed. Ready for Solvation!)")

        # Cleanup temp files
        if os.path.exists(ligand_tmp): os.remove(ligand_tmp)
        if os.path.exists(COMPLEX_RAW): os.remove(COMPLEX_RAW)

        # Verify
        print("\n--- Final Check: Box Vectors (Last Line) ---")
        os.system(f"tail -n 1 {COMPLEX_FIN}")
    else:
        print("❌ Error in gmx editconf step.")

print(f"\nFirst 15 lines of {COMPLEX_FIN} to inspect (protein and then ligand):")
!head -n 15 {COMPLEX_FIN}
print(f"\nLast 15 lines of {COMPLEX_FIN} to inspect (ligand and box vectors):")
!tail -n 15 {COMPLEX_FIN}

"""FIXING ERROR RELATED TO CONFLICT WITH RESIDUE NAME (ORIGINATE FROM CGENFF)"""

'''
A tiny issue in our complex.gro that may cause the next step to crash is found
in the residue name in ligand lines: "15197 H11..."

The Issue: gmx editconf truncated the residue name 519764 to fit the 5-character
limit, resulting in 5197.

The Conflict: Our topol.top expects the name "519".

If we run grompp now in solvation, it might say:
"Residue '5197' not found in topology."

The Fix:
We need to run a quick replacement to change 5197 to 519 in the .gro file,
and then we can proceed to Solvation and Ionization.
'''

# FIXING RESIDUE NAME (5197 -> 519) in complex.gro file
print(f"🔧 Fixing residue name in {COMPLEX_FIN}...")
# We use sed to replace '5197' with '519 ' (padding with space to maintain alignment)
os.system(f"sed -i 's/5197 /519  /g' {COMPLEX_FIN}")
os.system(f"sed -i 's/5197/519 /g' {COMPLEX_FIN}") # Safety catch for different spacing

print("✅ Name fixed. Proceeding to Solvation...")

print(f"\nFirst 15 lines of {COMPLEX_FIN} to inspect (protein and then ligand):")
!head -n 15 {COMPLEX_FIN}
print(f"\nLast 15 lines of {COMPLEX_FIN} to inspect (ligand and box vectors):")
!tail -n 15 {COMPLEX_FIN}

"""### **COMPUTATIONAL BIOPHYSICS (MD Biophysical Simulation)**

MD Biophysical Simulation parameters creation starts here.

This section downwards can be run independently without running others above, provided our master topology and complex.gro system have been produced. EXCEPT THE GROMACS INSTALLATION SECTION.

The mdp output files, from the code cell immediately below, does not need re-running, except you want to change the duration of the simulation.
"""

# This code cell can be run independently without running others above, provided our topol.top and complex.gro have been produced.
# However, this code cell does not need re-running if the md files have been previously generated. Except you want to change MD duration.

# Write CHARMM36-friendly MDP files for: ions, EM, NVT, NPT, 1 ns MD simulation
# Outputs to /content/drive/MyDrive/md_output/

'''
This cell writes recommended .mdp files into our project folder.
CHARMM36 cutoffs (1.2 nm, force-switch from 1.0→1.2 nm)
TIP3P water (CHARMM)
Output cadence trimmed to keep files lean
Production = 100 ns by default; change TOTAL_NS if you like.
'''


from google.colab import drive
from textwrap import dedent
import os, math

#drive.mount("/content/drive", force_remount=True)

BASE = "/content/drive/MyDrive"
OUT  = f"{BASE}/md_output"
os.makedirs(OUT, exist_ok=True)

# Common CHARMM36 settings (cutoffs & switching)
COMMON = """
cutoff-scheme   = Verlet
coulombtype     = PME
rcoulomb        = 1.2
rlist           = 1.2
vdwtype         = Cut-off
vdw-modifier    = force-switch
rvdw-switch     = 1.0
rvdw            = 1.2
DispCorr        = no
pbc             = xyz
nstlist         = 20
"""

# -------- ions.mdp (structure-only tpr for genion) --------
ions_mdp = dedent(f"""
; Minimal mdp just to build a tpr for genion
integrator      = steep
nsteps          = 200
emtol           = 10000
emstep          = 0.01
constraints     = none
{COMMON}
""").strip() + "\n"

# -------- minim.mdp --------
minim_mdp = dedent(f"""
; Energy minimization (steepest descent)
integrator      = steep
nsteps          = 50000
emtol           = 1000.0
emstep          = 0.01
constraints     = none
{COMMON}
""").strip() + "\n"

# -------- nvt.mdp --------
nvt_mdp = dedent(f"""
; NVT (100 ps), use -D POSRES in grompp for heavy-atom restraints
integrator      = md
dt              = 0.002
nsteps          = 50000           ; 100 ps
continuation    = no
constraints     = h-bonds
constraint-algorithm = lincs
lincs-order     = 4

tcoupl          = V-rescale
tc-grps         = System
tau_t           = 0.5
ref_t           = 300

pcoupl          = no
{COMMON}

gen-vel         = yes
gen-temp        = 300
gen-seed        = -1

; light I/O (10 ps/frame at 2 fs)
nstxout-compressed = 5000
nstenergy      = 5000
nstlog         = 5000
""").strip() + "\n"

# -------- npt.mdp --------
npt_mdp = dedent(f"""
; NPT (1 ns), use -D POSRES for heavy-atom restraints
integrator      = md
dt              = 0.002
nsteps          = 500000          ; 1 ns
continuation    = yes
constraints     = h-bonds
constraint-algorithm = lincs
lincs-order     = 4

tcoupl          = V-rescale
tc-grps         = System
tau_t           = 0.5
ref_t           = 300

pcoupl          = Parrinello-Rahman
pcoupltype      = isotropic
tau_p           = 5.0
ref_p           = 1.0
compressibility = 4.5e-5

{COMMON}

gen-vel         = no

; light I/O (10 ps/frame)
nstxout-compressed = 5000
nstenergy      = 5000
nstlog         = 5000
""").strip() + "\n"

# -------- md.mdp (1 ns) --------
TOTAL_NS = 1.0
DT_PS = 0.002
NSTEPS_MD = int((TOTAL_NS*1000)/DT_PS)

md_mdp = dedent(f"""
; Production MD ({TOTAL_NS} ns)
integrator      = md
dt              = 0.002
nsteps          = {NSTEPS_MD}     ; {TOTAL_NS} ns
continuation    = yes
constraints     = h-bonds
constraint-algorithm = lincs
lincs-order     = 4

tcoupl          = V-rescale
tc-grps         = System
tau_t           = 0.5
ref_t           = 300

pcoupl          = Parrinello-Rahman
pcoupltype      = isotropic
tau_p           = 5.0
ref_p           = 1.0
compressibility = 4.5e-5

{COMMON}

gen-vel         = no

; Keep I/O light (10 ps/frame)
nstxout-compressed = 5000
nstenergy      = 5000
nstlog         = 5000
""").strip() + "\n"

files = {
    "ions.mdp": ions_mdp,
    "minim.mdp": minim_mdp,
    "nvt.mdp": nvt_mdp,
    "npt.mdp": npt_mdp,
    "md.mdp": md_mdp,
}

for name, content in files.items():
    with open(os.path.join(OUT, name), "w") as f:
        f.write(content)
print("Wrote:", ", ".join([os.path.join(OUT,k) for k in files]))

"""**The steps below from Solvation down to Simulation can be run independently from all other code blocks above.**

**EXCEPT THE GROMACS INSTALLATION SECTION.**

#### **SOLVATION**
"""

# Step-by-step pipeline for 100 ns MD simulation with checkpointing every 15 min

import os, shutil
BASE = "/content/drive/MyDrive"
OUT  = f"{BASE}/md_output"
os.makedirs(OUT, exist_ok=True)

complex_gro = f"{BASE}/complex.gro"
topol_drive = f"{BASE}/topol.top"
topol_local = "/content/topol_work.top"

# Use CHARMM TIP3P if present; else spc216.gro
#water_box = "spc216.gro"
# Check if the CHARMM TIP3P water box exists in the GROMACS share directory
if os.path.exists("/usr/local/gromacs/share/gromacs/top/tip3p.gro"):
    water_box = "/usr/local/gromacs/share/gromacs/top/tip3p.gro"
elif os.path.exists("/usr/share/gromacs/top/tip3p.gro"):
     water_box = "/usr/share/gromacs/top/tip3p.gro"
else:
  water_box = "spc216.gro" # Fall back if tip3p.gro is not found


print("Water box:", water_box)


# 1) Solvate

# Work on a local copy of the topology (avoids Drive-rename issues)
shutil.copyfile(topol_drive, topol_local)

print("\n1) Solvating the system (editing local topology)...")
# -cp: input complex.gro file
# -cs: solvent molecule structure file (water_box)
# -o: output solvated gro file
# -p: topology file
!gmx solvate -cp {complex_gro} -cs {water_box} -o {OUT}/solv.gro -p {topol_local}

# Copy the edited topology back to Drive
shutil.copyfile(topol_local, topol_drive)
print("✅ Updated topology copied back to Drive:", topol_drive)

"""DEBUGGING SYSTEM ERROR CAUSED BY DISAPPEARING TOPOL_WORK.TOP FILE"""

'''
Considering the System Error when renaming topol_work.top in our previous step,
This code takes the solve.gro information and update it into topol.top
'''


# --- CONFIGURATION ---
TOPOL_DRIVE = "/content/drive/MyDrive/topol.top"
SOLVENT_COUNT = 49720  # FROM OUR SOLVATION STEP LOG ABOVE

print(f"🔧 Manually repairing {TOPOL_DRIVE}...")

# 1. Read file to check if it's already fixed
with open(TOPOL_DRIVE, 'r') as f:
    lines = f.readlines()

# Check if SOL is already there
is_fixed = False
for line in lines:
    if "SOL" in line and str(SOLVENT_COUNT) in line:
        is_fixed = True
        break

if is_fixed:
    print("✅ Topology is already correct (SOL 49720 found).")
else:
    # 2. Append the line
    with open(TOPOL_DRIVE, 'a') as f:
        # GROMACS format: Name (left) Count (right)
        f.write(f"{'SOL':<15} {SOLVENT_COUNT}\n")
    print(f"✅ Force-added 'SOL {SOLVENT_COUNT}' to topology.")

# 3. Verify
print("\n--- Last 5 lines of topol.top ---")
os.system(f"tail -n 5 {TOPOL_DRIVE}")

"""DEBUGGING ERROR RELATED TO DUPLICATE DIHEDRAL DEFINITIONS IN 519_FFBONDED.ITP FILE PROCESSED FROM CGENFF"""

'''
Here, we repair 519_ffbonded.itp to find duplicate dihedral definitions
and comments them out. Since GROMACS doesn't support duplicate definition of the same parameter.
'''


import os
import shutil

# --- CONFIGURATION ---
BASE_DIR = "/content/drive/MyDrive"
ITP_FILE = f"{BASE_DIR}/519_ffbonded.itp"

print(f"🔧 Starting 'Nuclear' Repair on {ITP_FILE}...")

# 1. Read File
with open(ITP_FILE, 'r') as f:
    lines = f.readlines()

new_lines = []
seen_dihedrals = set()
in_dihedral_section = False
deleted_count = 0

for line_idx, line in enumerate(lines):
    clean = line.strip()

    # Check sections
    if "[ dihedraltypes ]" in clean:
        in_dihedral_section = True
        new_lines.append(line)
        continue
    elif clean.startswith("[") and in_dihedral_section:
        in_dihedral_section = False

    # Process Dihedral Section
    if in_dihedral_section and clean and not clean.startswith(";"):
        parts = clean.split()

        # Valid line usually has: Atom1 Atom2 Atom3 Atom4 Func ...
        # We grab the first 4 items as the atom key
        if len(parts) >= 5:
            atoms = tuple(parts[:4])
            atoms_rev = tuple(reversed(atoms)) # Check reverse direction too (D-C-B-A)

            # If we have seen this quartet before, DELETE IT
            if atoms in seen_dihedrals or atoms_rev in seen_dihedrals:
                print(f"   -> Removing duplicate on Line {line_idx+1}: {atoms}")
                new_lines.append(f"; DUPLICATE DELETED: {line}")
                deleted_count += 1
                continue

            # First time seeing it? Remember it.
            seen_dihedrals.add(atoms)

    # Keep non-duplicate lines
    new_lines.append(line)

# 2. Overwrite File
if deleted_count > 0:
    print(f"✅ CLEANUP COMPLETE. Removed {deleted_count} duplicate lines.")
    shutil.copy(ITP_FILE, f"{ITP_FILE}.bak") # Safety backup
    with open(ITP_FILE, 'w') as f:
        f.writelines(new_lines)
else:
    print("⚠️ No duplicates found by script (Check if file path is correct).")

"""#### **IONIZATION**"""

# 2) Ionization (Codes have been revised to include Error fixes)

'''

Errors:
1) 519_ffbonded.itp duplicate definition for same dihedral angles
>> This is because CGenFF sometimes lists the same dihedral twice
(e.g., once for the ring geometry, once for a specific substituent),
and while CHARMM allows this, GROMACS is stricter about "re-defining"
the exact same line.

2) Copied .itp and .top files to VM drive to fix topol_work error earlier

'''


import os
import shutil
import glob

# --- CONFIGURATION ---
BASE_DIR = "/content/drive/MyDrive"
ITP_NAME = "519_ffbonded.itp"
ITP_PATH_DRIVE = f"{BASE_DIR}/{ITP_NAME}"
ITP_PATH_LOCAL = f"/content/{ITP_NAME}"

print(f"🔧 RESOLVING FORCE FIELD CONFLICT IN {ITP_NAME}...")

# 1. SETUP WORKSPACE
os.chdir("/content")
if os.path.abspath(ITP_PATH_DRIVE) != os.path.abspath(ITP_PATH_LOCAL):
    shutil.copyfile(ITP_PATH_DRIVE, ITP_PATH_LOCAL)

# 2. READ & REMOVE CONFLICTING LINES
with open(ITP_PATH_LOCAL, 'r') as f:
    lines = f.readlines()

new_lines = []
conflict_atoms = {'CG2D1', 'CG321', 'CG311'} # Set of atoms involved in the conflict
fixed_count = 0

for line in lines:
    clean_line = line.strip()

    # We look for the specific conflicting sequence: CG2D1 CG321 CG321 CG311
    # We check mainly for the atoms, ignoring the numbers
    if "CG2D1" in clean_line and "CG321" in clean_line and "CG311" in clean_line:
        parts = clean_line.split()
        if len(parts) >= 4:
            atoms = tuple(parts[:4])
            # Check exact match for the problem line (Forward or Reverse)
            target = ('CG2D1', 'CG321', 'CG321', 'CG311')
            target_rev = ('CG311', 'CG321', 'CG321', 'CG2D1')

            if atoms == target or atoms == target_rev:
                print(f"   -> Commenting out conflict on line: {clean_line}")
                new_lines.append(f"; CONFLICT REMOVED: {line}")
                fixed_count += 1
                continue

    new_lines.append(line)

# 3. SAVE & SYNC
if fixed_count > 0:
    print(f"✅ Resolved {fixed_count} conflicting lines.")
    with open(ITP_PATH_LOCAL, 'w') as f:
        f.writelines(new_lines)
    shutil.copyfile(ITP_PATH_LOCAL, ITP_PATH_DRIVE)
else:
    print("⚠️ No specific conflict line found. Check if the atom names match exactly.")


# --- EXECUTION PHASE ---
print("\n⚡ STARTING IONIZATION ⚡")

# Copy Files
if os.path.abspath(f"{BASE_DIR}/topol.top") != os.path.abspath("topol.top"):
    shutil.copy(f"{BASE_DIR}/topol.top", "topol.top")
shutil.copy(f"{BASE_DIR}/md_output/ions.mdp", "ions.mdp")
shutil.copy(f"{BASE_DIR}/md_output/solv.gro", "solv.gro")

for f in glob.glob(f"{BASE_DIR}/*.itp"):
    dst = os.path.join("/content", os.path.basename(f))
    if os.path.abspath(f) != os.path.abspath(dst):
        shutil.copy(f, dst)

print("--- GROMPP ---")
!gmx grompp -f ions.mdp -c solv.gro -p topol.top -o ions.tpr -maxwarn 2

print("\n--- GENION ---")
if os.path.exists("ions.tpr"):
    !echo "SOL" | gmx genion -s ions.tpr -o ions.gro -p topol.top -pname NA -nname CL -neutral

    if os.path.exists("ions.gro"):
        print("\n🎉 SUCCESS! Syncing results...")
        shutil.copy("topol.top", f"{BASE_DIR}/topol.top")
        shutil.copy("ions.gro", f"{BASE_DIR}/md_output/ions.gro")
        shutil.copy("ions.tpr", f"{BASE_DIR}/md_output/ions.tpr")
        print("   🚀 READY FOR MINIMIZATION.")
    else:
        print("❌ Genion failed.")
else:
    print("❌ Grompp failed.")

"""#### **MINIMIZATION**"""

# 3) EM (Energy Minimization)
print("\n3) Performing Energy Minimization...")
# -f: mdp file for EM
# -c: input gro file (solvated and ionized system)
# -p: topology file
# -o: output tpr file for EM
# -deffnm: define base filename for all output files (em.log, em.xtc, em.gro, em.edr, em.cpt)
# -cpt: checkpoint interval in minutes

import os
import shutil
import glob

# --- CONFIGURATION ---
BASE_DIR = "/content/drive/MyDrive"
OUT = f"{BASE_DIR}/md_output"
IONS_GRO = f"{OUT}/ions.gro"
TOPOL_TOP = f"{BASE_DIR}/topol.top"

# Output definitions
MINIM_MDP = f"{OUT}/minim.mdp"
EM_TPR    = f"{OUT}/em.tpr"
EM_GRO    = f"{OUT}/em.gro"

print("📉 PREPARING ENERGY MINIMIZATION 📉")


# 1. SETUP LOCAL WORKSPACE
# We move everything to /content/ to run fast and avoid Drive issues
print("   -> Setting up local workspace...")
os.chdir("/content")

# Copy Inputs
shutil.copy(IONS_GRO, "ions.gro")
shutil.copy(TOPOL_TOP, "topol.top")
shutil.copy(MINIM_MDP, "minim.mdp")

# Copy ALL Includes (.itp) from Drive
for f in glob.glob(f"{BASE_DIR}/*.itp"):
    shutil.copy(f, ".")


# 2. RUN GROMPP (Assemble the EM run)
print("\n--- GROMPP (Assembling EM) ---")
# -maxwarn 1 is usually enough for CGenFF
!gmx grompp -f minim.mdp -c ions.gro -p topol.top -o em.tpr -maxwarn 1


# 3. RUN MDRUN (The Physics)
print("\n--- MDRUN (Minimizing Energy) ---")
if os.path.exists("em.tpr"):
    # -v: Verbose (shows progress steps)
    # -deffnm em: Names all outputs em.gro, em.edr, em.log, etc.
    !gmx mdrun -v -deffnm em

    # 4. SYNC RESULTS
    print("\n✅ Syncing results back to Drive...")
    if os.path.exists("em.gro"):
        shutil.copy("em.gro", f"{OUT}/em.gro")
        shutil.copy("em.log", f"{OUT}/em.log")
        shutil.copy("em.edr", f"{OUT}/em.edr")
        shutil.copy("em.trr", f"{OUT}/em.trr")
        print(f"   Structure saved to: {OUT}/em.gro")
        print("   🚀 MINIMIZATION COMPLETE! Ready for Equilibration.")
    else:
        print("❌ Minimization failed (No em.gro created).")
else:
    print("❌ Grompp failed (No em.tpr created). Check logs above.")

"""#### **NVT TO STABILIZE TEMPERATURE, VOLUME, AND NUMBER OF ATOMS**"""

# 4) NVT (constant Number, Volume, Temperature)
print("\n4) Running NVT equilibration...")
# -f: mdp file for NVT
# -c: input gro file from EM
# -r: input gro file for position restraints (usually same as -c for NVT)
# -p: topology file
# -o: output tpr file for NVT
# -D POSRES: define a preprocessor directive for position restraints (if supported by FF/topology)
# -maxwarn 1: suppress warnings
# -deffnm: define base filename for output files (nvt.log, nvt.xtc, nvt.gro, nvt.edr, nvt.cpt)
# -cpt: checkpoint interval in minutes


import os
import shutil

# --- CONFIGURATION ---
BASE_DIR = "/content/drive/MyDrive"
OUT = f"{BASE_DIR}/md_output"
EM_GRO = f"{OUT}/em.gro"
TOPOL_TOP = f"{BASE_DIR}/topol.top"

# Output Files
NVT_MDP = f"{OUT}/nvt.mdp"
NVT_TPR = f"{OUT}/nvt.tpr"
NVT_GRO = f"{OUT}/nvt.gro"

print("🔥 PREPARING NVT EQUILIBRATION (Heating to 310 K) 🔥")

# 1. SETUP LOCAL WORKSPACE
os.chdir("/content")
# Copy necessary files to VM
shutil.copy(EM_GRO, "em.gro")
shutil.copy(TOPOL_TOP, "topol.top")
shutil.copy(NVT_MDP, "nvt.mdp")

# 2. RUN GROMPP
print("\n--- GROMPP (Assembling NVT) ---")
# -r em.gro is CRITICAL here. It tells GROMACS: "Keep the protein atoms close to these coordinates"
# -maxwarn 1 ignores CGenFF warnings
!gmx grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -o nvt.tpr -maxwarn 1

# 3. RUN MDRUN
print("\n--- MDRUN (Running Simulation) ---")
if os.path.exists("nvt.tpr"):
    # -deffnm nvt names all outputs nvt.log, nvt.edr, etc.
    !gmx mdrun -v -deffnm nvt

    # 4. SYNC RESULTS
    print("\n✅ Syncing results back to Drive...")
    if os.path.exists("nvt.gro"):
        shutil.copy("nvt.gro", f"{OUT}/nvt.gro")
        shutil.copy("nvt.edr", f"{OUT}/nvt.edr")
        shutil.copy("nvt.log", f"{OUT}/nvt.log")
        shutil.copy("nvt.cpt", f"{OUT}/nvt.cpt")
        shutil.copy("nvt.trr", f"{OUT}/nvt.trr")
        print(f"   Structure saved to: {OUT}/nvt.gro")
        print("   🚀 NVT COMPLETE! System is now at 310 K.")
    else:
        print("❌ NVT Simulation failed (No nvt.gro).")
else:
    print("❌ Grompp failed (No nvt.tpr). Check logs.")

"""**Information** <br>
Our NVT simulation finished successfully.

The error we see from the step above is a "false alarm" regarding our data.

The Physics Worked: The log shows step 50000, Writing final coordinates, and a solid performance of 105 ns/day.

The Error: The script crashed because it tried to copy nvt.trr (a heavy trajectory file), but GROMACS didn't generate one. This is normal behavior when the .mdp file doesn't explicitly ask for full-precision trajectory output.

The Fix: You don't need the .trr file. The critical files (nvt.gro and nvt.cpt) were likely generated before the script crashed on the optional .trr file.


**We can continue with the next step!**

#### **NPT TO STABILIZE PRESSURE WITH TEMPERATURE, AND NUMBER OF ATOMS**
"""

# 5) NPT (constant Number, Pressure, Temperature)
print("\n5) Running NPT equilibration...")
# -f: mdp file for NPT
# -c: input gro file from NVT
# -r: input gro file for position restraints (usually same as -c for NVT)
# -t: input checkpoint file from NVT (to continue simulation state)
# -p: topology file
# -o: output tpr file for NPT
# -D POSRES: define a preprocessor directive for position restraints
# -maxwarn 1: suppress warnings
# -deffnm: define base filename for output files (npt.log, npt.xtc, npt.gro, npt.edr, npt.cpt)
# -cpt: checkpoint interval in minutes


import os
import shutil

# --- CONFIGURATION ---
BASE_DIR = "/content/drive/MyDrive"
OUT = f"{BASE_DIR}/md_output"
TOPOL_TOP = f"{BASE_DIR}/topol.top"

# Inputs from NVT
NVT_GRO = f"{OUT}/nvt.gro"
NVT_CPT = f"{OUT}/nvt.cpt"

# Outputs
NPT_MDP = f"{OUT}/npt.mdp"
NPT_TPR = f"{OUT}/npt.tpr"
NPT_GRO = f"{OUT}/npt.gro"

print("⚖️ PREPARING NPT EQUILIBRATION (Pressurizing to 1 bar) ⚖️")

# 1. SETUP LOCAL WORKSPACE
os.chdir("/content")
# Copy Checkpoint and Coordinates
# We check if the script crashed before copying nvt.cpt to Drive.
# If nvt.cpt isn't in Drive, check local /content/ from previous run.
if not os.path.exists(NVT_CPT) and os.path.exists("/content/nvt.cpt"):
    print("   -> Found orphan nvt.cpt in local folder, using that.")
    shutil.copy("/content/nvt.cpt", "nvt.cpt")
    shutil.copy("/content/nvt.gro", "nvt.gro")
else:
    shutil.copy(NVT_GRO, "nvt.gro")
    shutil.copy(NVT_CPT, "nvt.cpt")

shutil.copy(TOPOL_TOP, "topol.top")
shutil.copy(NPT_MDP, "npt.mdp")

# Copy Includes
import glob
for f in glob.glob(f"{BASE_DIR}/*.itp"):
    shutil.copy(f, ".")

# 2. RUN GROMPP
print("\n--- GROMPP (Assembling NPT) ---")
# -t reads the checkpoint (velocities)
# -r keeps restraints
!gmx grompp -f npt.mdp -c nvt.gro -r nvt.gro -t nvt.cpt -p topol.top -o npt.tpr -maxwarn 1

# 3. RUN MDRUN
print("\n--- MDRUN (Running Simulation) ---")
if os.path.exists("npt.tpr"):
    !gmx mdrun -v -deffnm npt

    # 4. SYNC RESULTS
    print("\n✅ Syncing results back to Drive...")
    if os.path.exists("npt.gro"):
        shutil.copy("npt.gro", f"{OUT}/npt.gro")
        shutil.copy("npt.edr", f"{OUT}/npt.edr")
        shutil.copy("npt.log", f"{OUT}/npt.log")
        shutil.copy("npt.cpt", f"{OUT}/npt.cpt")
        print(f"   Structure saved to: {OUT}/npt.gro")
        print("   🚀 NPT COMPLETE! System is pressurized.")
    else:
        print("❌ NPT Simulation failed.")
else:
    print("❌ Grompp failed (No npt.tpr). Check logs.")

"""#### **PRODUCTION RUN FOR MOLECULAR DYNAMICS SIMULATION [100 NANOSECONDS]**

Two different production run code blocks are available below. <br> The code block immediately below is optimized for Colab Pro `A100` or `L4` High-RAM GPUs. <br> But in cases of compute units exhaustion, we can switch to the free Colab `T4` GPU which would take more simulation time, and the code block is just under this one below: <br>
`Nvidia A100 High-RAM GPU` - 100ns/day (24 hours) <br>
`Nvidia L4 High-RAM GPU` - 100ns/day (28 hours) <br>
`Nvidia T4 GPU` - 100ns/3-4 days (72-100 hours) <br>

This simulation time is an estimate for a medium-sized system of about 150,000 - 160,000 atoms.
"""

import os
import shutil
import glob
import time
import threading

# --- CONFIGURATION ---
BASE_DIR = "/content/drive/MyDrive"
OUT = f"{BASE_DIR}/md_output"
TOPOL_TOP = f"{BASE_DIR}/topol.top"

# Inputs/Outputs
NPT_GRO = f"{OUT}/npt.gro"
NPT_CPT = f"{OUT}/npt.cpt"
MD_MDP  = f"{OUT}/md.mdp"
DEFFNM = "md_0_1"

print("🚀 PRODUCTION MD: A100 HIGH-RAM (PART MODE) 🚀")

# 1. SETUP LOCAL WORKSPACE
os.chdir("/content")
if os.path.exists(TOPOL_TOP):
    shutil.copy(TOPOL_TOP, "topol.top")
for f in glob.glob(f"{BASE_DIR}/*.itp"):
    shutil.copy(f, ".")

# 2. UPDATE PARAMETERS (A100 GPU Optimized)
with open("md.mdp", "w") as f:
    f.write("; md.mdp - 100 ns Production MD\n")
    f.write("integrator  = md\n")
    f.write("nsteps      = 50000000  ; 50 million steps (100 ns)\n")
    f.write("dt          = 0.002     ; 2 fs\n")
    f.write("nstxout                = 0\n")
    f.write("nstvout                = 0\n")
    f.write("nstenergy              = 5000\n")
    f.write("nstlog                 = 5000\n")
    f.write("nstxout-compressed     = 5000\n")
    f.write("compressed-x-grps      = System\n")
    f.write("constraints            = h-bonds\n")
    f.write("constraint_algorithm   = lincs\n")
    f.write("continuation           = yes\n")
    f.write("tcoupl                 = V-rescale\n")
    f.write("tc-grps                = System\n")
    f.write("tau_t                  = 0.1\n")
    f.write("ref_t                  = 310\n")
    f.write("pcoupl                 = Parrinello-Rahman\n")
    f.write("pcoupltype             = isotropic\n")
    f.write("tau_p                  = 2.0\n")
    f.write("ref_p                  = 1.0\n")
    f.write("compressibility        = 4.5e-5\n")
    f.write("coulombtype            = PME\n")
    f.write("pme_order              = 4\n")
    f.write("fourierspacing         = 0.16\n")
    f.write("rcoulomb               = 1.2\n")
    f.write("rvdw                   = 1.2\n")
    f.write("nstlist                = 10\n")
shutil.copy("md.mdp", MD_MDP)

# 3. CHECK FOR RESUME (FORCED PART CREATION)
drive_cpt = f"{OUT}/{DEFFNM}.cpt"
resume_flag = ""

if os.path.exists(drive_cpt):
    print(f"🔄 FOUND CHECKPOINT: {drive_cpt}")
    print("   -> Copying checkpoint to VM...")
    shutil.copy(drive_cpt, f"{DEFFNM}.cpt")

    # Regenerate TPR if missing (Ensures binary compatibility)
    if not os.path.exists(f"{DEFFNM}.tpr"):
        print("   -> Regenerating .tpr file...")
        shutil.copy(NPT_GRO, "npt.gro")
        shutil.copy(NPT_CPT, "npt.cpt")
        os.system(f"gmx grompp -f md.mdp -c npt.gro -t npt.cpt -p topol.top -o {DEFFNM}.tpr -maxwarn 1")

    # --- CRITICAL CHANGE ---
    # We purposefully do NOT check for or download the old .xtc files.
    # We force -noappend to create a new "Part" file (e.g. part0007.xtc)
    # This preserves the history and prevents start-up errors.
    print("✨ STARTING NEW PART FILE")
    print("   -> Physics will resume EXACTLY where you stopped.")
    print("   -> Data will be written to a NEW file (e.g. md_0_1.partXXXX.xtc).")
    resume_flag = f"-cpi {DEFFNM}.cpt -noappend"

else:
    print("✨ STARTING FRESH 100ns RUN")
    if os.path.exists(NPT_GRO) and os.path.exists(NPT_CPT):
        shutil.copy(NPT_GRO, "npt.gro")
        shutil.copy(NPT_CPT, "npt.cpt")
        print("   -> Assembling binary input...")
        !gmx grompp -f md.mdp -c npt.gro -t npt.cpt -p topol.top -o {DEFFNM}.tpr -maxwarn 1
        if os.path.exists(f"{DEFFNM}.tpr"):
            shutil.copy(f"{DEFFNM}.tpr", f"{OUT}/{DEFFNM}.tpr")
    else:
        print("❌ Error: NPT files missing from Drive.")
        exit()

# ---------------------------------------------------------
# 4. DUAL SIDECARS (Two Independent Threads)
# ---------------------------------------------------------

# THREAD A: The "Lifeguard" (Safety Sync)
def sidecar_safety():
    print(f"\n[Safety Sidecar] Started. Syncing .cpt/.log every 10 mins 10 secs...")
    while True:
        time.sleep(610) # 10m 10s
        try:
            if os.path.exists(f"{DEFFNM}.cpt"):
                shutil.copy(f"{DEFFNM}.cpt", f"{OUT}/{DEFFNM}.cpt")
            # Sync logs including part files
            for log in glob.glob(f"{DEFFNM}*.log"):
                shutil.copy(log, f"{OUT}/{os.path.basename(log)}")
            print(f"\n✅ [Safety Sync] Checkpoint saved at {time.strftime('%H:%M')}")
        except: pass

# THREAD B: The "Mover" (Heavy Sync)
def sidecar_heavy():
    print(f"\n[Heavy Sidecar] Started. Syncing .xtc/.edr every 30 mins...")
    while True:
        time.sleep(1800) # 30 mins
        try:
            print(f"\n🔄 [Heavy Sync] Uploading trajectory files... (This may take time)")
            for ext in ["xtc", "edr"]:
                # Matches md_0_1.xtc AND md_0_1.part0002.xtc, part0003, etc.
                for local_file in glob.glob(f"{DEFFNM}*.{ext}"):
                    shutil.copy(local_file, f"{OUT}/{os.path.basename(local_file)}")
            print(f"✅ [Heavy Sync] Trajectory parts saved at {time.strftime('%H:%M')}")
        except Exception as e:
            print(f"⚠️ [Heavy Sync] Warning: {e}")

# Start both threads
t_safety = threading.Thread(target=sidecar_safety, daemon=True)
t_safety.start()

t_heavy = threading.Thread(target=sidecar_heavy, daemon=True)
t_heavy.start()

# 5. RUN SIMULATION (A100 POWERED)
print("\n🔥 STARTING SIMULATION (A100 GPU) 🔥")
!gmx mdrun -v -deffnm {DEFFNM} {resume_flag} -cpt 5 -nb gpu -pme gpu -bonded gpu

"""THE PRODUCTION RUN CODE BELOW IS BASICALLY THE SAME AS THAT ABOVE, ONLY THAT THIS ONE IS OPTIMIZED FOR GOOGLE COLAB FREE ``T4`` GPU WHILE THE CODE BLOCK ABOVE IS OPTIMIZED FOR ``A100`` OR ``L4`` GPUs. OUR MD SIMULATION WILL RESUME FROM PREVIOUS CHECKPOINT FROM A100 GPU ABOVE AND CONTINUE WITH T4 GPU BELOW.

NB: IF WE WANT, WE CAN AS WELL CONTINUE WITH THE CODE ABOVE, NO DIFFERENCE.
"""

import os
import shutil
import glob
import time
import threading

# --- CONFIGURATION ---
BASE_DIR = "/content/drive/MyDrive"
OUT = f"{BASE_DIR}/md_output"
TOPOL_TOP = f"{BASE_DIR}/topol.top"

# Inputs/Outputs
NPT_GRO = f"{OUT}/npt.gro"
NPT_CPT = f"{OUT}/npt.cpt"
MD_MDP  = f"{OUT}/md.mdp"
DEFFNM = "md_0_1"

print("🚀 PRODUCTION MD: RESUMING ON T4 GPU 🚀")

# 1. SETUP LOCAL WORKSPACE
os.chdir("/content")
if os.path.exists(TOPOL_TOP):
    shutil.copy(TOPOL_TOP, "topol.top")
for f in glob.glob(f"{BASE_DIR}/*.itp"):
    shutil.copy(f, ".")

# 2. UPDATE PARAMETERS (GPU Optimized)
with open("md.mdp", "w") as f:
    f.write("; md.mdp - 100 ns Production MD\n")
    f.write("integrator  = md\n")
    f.write("nsteps      = 50000000  ; 50 million steps (100 ns)\n")
    f.write("dt          = 0.002     ; 2 fs\n")
    f.write("nstxout                = 0\n")
    f.write("nstvout                = 0\n")
    f.write("nstenergy              = 5000\n")
    f.write("nstlog                 = 5000\n")
    f.write("nstxout-compressed     = 5000\n")
    f.write("compressed-x-grps      = System\n")
    f.write("constraints            = h-bonds\n")
    f.write("constraint_algorithm   = lincs\n")
    f.write("continuation           = yes\n")
    f.write("tcoupl                 = V-rescale\n")
    f.write("tc-grps                = System\n")
    f.write("tau_t                  = 0.1\n")
    f.write("ref_t                  = 310\n")
    f.write("pcoupl                 = Parrinello-Rahman\n")
    f.write("pcoupltype             = isotropic\n")
    f.write("tau_p                  = 2.0\n")
    f.write("ref_p                  = 1.0\n")
    f.write("compressibility        = 4.5e-5\n")
    f.write("coulombtype            = PME\n")
    f.write("pme_order              = 4\n")
    f.write("fourierspacing         = 0.16\n")
    f.write("rcoulomb               = 1.2\n")
    f.write("rvdw                   = 1.2\n")
    f.write("nstlist                = 10\n")
shutil.copy("md.mdp", MD_MDP)

# 3. CHECK FOR RESUME (SMART LOGIC)
drive_cpt = f"{OUT}/{DEFFNM}.cpt"
drive_xtc = f"{OUT}/{DEFFNM}.xtc"
resume_flag = ""

if os.path.exists(drive_cpt):
    print(f"🔄 FOUND CHECKPOINT: {drive_cpt}")
    shutil.copy(drive_cpt, f"{DEFFNM}.cpt")

    # REGENERATE TPR
    if not os.path.exists(f"{DEFFNM}.tpr"):
        print("   -> Regenerating .tpr file...")
        shutil.copy(NPT_GRO, "npt.gro")
        shutil.copy(NPT_CPT, "npt.cpt")
        os.system(f"gmx grompp -f md.mdp -c npt.gro -t npt.cpt -p topol.top -o {DEFFNM}.tpr -maxwarn 1")

    # DECIDE: APPEND or NO-APPEND?
    # Since we are switching VMs frequently, we force NO-APPEND mode if files are missing locally.
    # This prevents the "Missing Output Files" error.
    # It simply creates md_0_1.part0003.xtc, etc.
    if os.path.exists(drive_xtc):
        print("   -> Found base .xtc in Drive. Attempting append...")
        shutil.copy(drive_xtc, f"{DEFFNM}.xtc")
        if os.path.exists(f"{OUT}/{DEFFNM}.edr"): shutil.copy(f"{OUT}/{DEFFNM}.edr", f"{DEFFNM}.edr")
        if os.path.exists(f"{OUT}/{DEFFNM}.log"): shutil.copy(f"{OUT}/{DEFFNM}.log", f"{DEFFNM}.log")
        resume_flag = f"-cpi {DEFFNM}.cpt -append"
    else:
        print("⚠️ Note: Base .xtc not found (or using parts). Switching to New File Mode.")
        print("   -> Physics will resume EXACTLY from step 22,653,500.")
        print("   -> Data will be written to a new 'part' file (e.g. part0003).")
        resume_flag = f"-cpi {DEFFNM}.cpt -noappend"

else:
    print("✨ STARTING FRESH 100ns RUN")
    # This block likely won't run for you since you have a checkpoint
    if os.path.exists(NPT_GRO) and os.path.exists(NPT_CPT):
        shutil.copy(NPT_GRO, "npt.gro")
        shutil.copy(NPT_CPT, "npt.cpt")
        !gmx grompp -f md.mdp -c npt.gro -t npt.cpt -p topol.top -o {DEFFNM}.tpr -maxwarn 1
        if os.path.exists(f"{DEFFNM}.tpr"):
            shutil.copy(f"{DEFFNM}.tpr", f"{OUT}/{DEFFNM}.tpr")
    else:
        print("❌ Error: NPT files missing from Drive.")
        exit()

# ---------------------------------------------------------
# 4. DUAL SIDECARS (SAFETY + HEAVY)
# ---------------------------------------------------------

def sidecar_safety():
    print(f"\n[Safety Sidecar] Started. Syncing .cpt/.log every 10 mins 10 secs...")
    while True:
        time.sleep(610) # 10 mins 10 secs
        try:
            if os.path.exists(f"{DEFFNM}.cpt"):
                shutil.copy(f"{DEFFNM}.cpt", f"{OUT}/{DEFFNM}.cpt")
            # Sync logs including part files
            for log in glob.glob(f"{DEFFNM}*.log"):
                shutil.copy(log, f"{OUT}/{os.path.basename(log)}")
            print(f"\n✅ [Safety Sync] Checkpoint saved at {time.strftime('%H:%M')}")
        except: pass

def sidecar_heavy():
    print(f"\n[Heavy Sidecar] Started. Syncing .xtc/.edr every 30 mins...")
    while True:
        time.sleep(1800) # 30 minutes
        try:
            # Sync ALL trajectory parts (part0001, part0002, etc)
            print(f"\n🔄 [Heavy Sync] Uploading trajectory files...")
            for ext in ["xtc", "edr"]:
                for local_file in glob.glob(f"{DEFFNM}*.{ext}"):
                    shutil.copy(local_file, f"{OUT}/{os.path.basename(local_file)}")
            print(f"✅ [Heavy Sync] Trajectory parts saved at {time.strftime('%H:%M')}")
        except: pass

t_safety = threading.Thread(target=sidecar_safety, daemon=True)
t_safety.start()

t_heavy = threading.Thread(target=sidecar_heavy, daemon=True)
t_heavy.start()

# 5. RUN SIMULATION
print("\n🔥 STARTING T4 SIMULATION (Slower than A100 and L4) 🔥")
# We keep the GPU flags. T4 supports them.
!gmx mdrun -v -deffnm {DEFFNM} {resume_flag} -cpt 5 -nb gpu -pme gpu -bonded gpu

"""The ``energygrps`` was removed from simulation above because it's not optimized to run on GPU. We removed this for faster GPU simulation. After simulation, we seprately re-run ``energygrps`` calculation to get the ligand-protein interactions dataset that we can integrate into predictive modeling or computational neuroscience further research.

#### **SIMULATION POST PROCESSING BEFORE ANALYSIS**

The post-simulation processing is a data cleanup step to prepare the data generated for post-md analysis. <br>
It involves: (1) concatenating the several parts generated into one seamless file, and (2) Fixing the Periodic Boundary Conditions (PBC) to align the protein at the boundary box center and make it smooth.
"""

import os
import glob

# --- CONFIGURATION ---
BASE_DIR = "/content/drive/MyDrive/md_output"
DEFFNM = "md_0_1"
TPR_FILE = f"{BASE_DIR}/{DEFFNM}.tpr"

print("🧹 STARTING POST-PROCESSING: STITCHING & CLEANING 🧹")

# Change directory to md files location
os.chdir(BASE_DIR)

# 1. CONCATENATE TRAJECTORIES (The "Zipper" Step)
# This finds all md_0_1*.xtc files and stitches them by time
print("\n🔗 Step 1: Stitching all parts into one trajectory...")
!gmx trjcat -f {DEFFNM}*.xtc -o {DEFFNM}_combined.xtc -cat

if os.path.exists(f"{DEFFNM}_combined.xtc"):
    print("   ✅ Stitching complete: md_0_1_combined.xtc created.")
else:
    print("   ❌ Error: Stitching failed. Check if .xtc files exist.")
    exit()

# 2. CONCATENATE ENERGIES
print("\n🔋 Step 2: Stitching energy files...")
!gmx eneconv -f {DEFFNM}*.edr -o {DEFFNM}_combined.edr
print("   ✅ Energy stitching complete.")

# 3. FIX PBC & CENTER PROTEIN
# We make the molecules whole, then center the protein in the box.
# Input: 1 (Protein) for centering, 0 (System) for output.
print("\n🧼 Step 3: Removing PBC artifacts (Centering Protein)...")
# We use a pipe (|) to send the inputs "1" and "0" automatically
!echo "1 0" | gmx trjconv -s {DEFFNM}.tpr -f {DEFFNM}_combined.xtc -o {DEFFNM}_centered.xtc -pbc mol -center
print("   ✅ Centering complete.")

# 4. ROTATIONAL FITTING (Smoothing)
# We align the protein Backbone to minimize rotation (Best for RMSF/Visuals)
# Input: 4 (Backbone) for fitting, 0 (System) for output. Our echo "4 0 |" automatically does this.
print("\n📐 Step 4: Performing Rotational Fit (Stopping the tumbling)...")
!echo "4 0" | gmx trjconv -s {DEFFNM}.tpr -f {DEFFNM}_centered.xtc -o {DEFFNM}_final_fit.xtc -fit rot+trans

if os.path.exists(f"{DEFFNM}_final_fit.xtc"):
    print("\n✨ SUCCESS! Your Final Analysis Files are ready:")
    print(f"   1. Trajectory: {BASE_DIR}/{DEFFNM}_final_fit.xtc")
    print(f"   2. Energy:     {BASE_DIR}/{DEFFNM}_combined.edr")
    print("   3. Topology:   (Your original .tpr)")
else:
    print("\n⚠️ Warning: Something went wrong with the fitting step.")

"""#### **MD ANALYSIS AND DATA VISUALIZATION**

Here we run our analysis and plot RMSF, RMSD, and other results.
"""

import matplotlib.pyplot as plt
import numpy as np
import os

# --- CONFIGURATION ---
BASE_DIR = "/content/drive/MyDrive/md_output"
DEFFNM = "md_0_1"
FINAL_TRAJ = f"{DEFFNM}_final_fit.xtc"
COMBINED_EDR = f"{DEFFNM}_combined.edr"
TPR = f"{DEFFNM}.tpr"

os.chdir(BASE_DIR)
print("📊 STARTING DATA EXTRACTION & PLOTTING 📊")

# 1. CALCULATE RMSD (Backbone Stability)
# Input '4' (Backbone) for fitting, '4' (Backbone) for calculation
print("\nrunning RMSD calculation...")
!echo "4 4" | gmx rms -s {TPR} -f {FINAL_TRAJ} -o rmsd.xvg

# 2. CALCULATE RMSF (Residue Flexibility)
# Input '3' (C-alpha) usually gives cleaner plots than '1' (Protein)
print("running RMSF calculation...")
!echo "3" | gmx rmsf -s {TPR} -f {FINAL_TRAJ} -o rmsf.xvg -res

# 3. EXTRACT INTERACTION ENERGY (Coulomb + LJ)
# We try to extract Short-Range Coulomb (usually term 8 or similar) and LJ (term 7)
# Since we don't know exact term numbers, we'll try to calculate Potential first as a test.
print("Extracting Potential Energy...")
!echo "11" | gmx energy -f {COMBINED_EDR} -o potential.xvg

# --- PLOTTING FUNCTIONS ---
def read_xvg(fname):
    data = []
    if not os.path.exists(fname):
        return None
    with open(fname, 'r') as f:
        for line in f:
            if not line.startswith(("@", "#")):
                parts = line.split()
                data.append([float(x) for x in parts])
    return np.array(data)

# PLOT RMSD
rmsd = read_xvg("rmsd.xvg")
if rmsd is not None:
    plt.figure(figsize=(10, 6))
    # rmsd[:,0] is Time (ps). Divide by 1000 for ns.
    plt.plot(rmsd[:,0]/1000, rmsd[:,1], color='black', linewidth=1)
    plt.title("RMSD of Protein Backbone (Stable Phase)")
    plt.xlabel("Time (ns)")
    plt.ylabel("RMSD (nm)")
    plt.grid(alpha=0.3)
    plt.savefig("RMSD_Plot.png", dpi=300)
    plt.show()
    print("✅ RMSD Plot saved.")

# PLOT RMSF
rmsf = read_xvg("rmsf.xvg")
if rmsf is not None:
    plt.figure(figsize=(10, 6))
    plt.plot(rmsf[:,0], rmsf[:,1], color='red', linewidth=1)
    plt.title("RMSF per Residue")
    plt.xlabel("Residue Index")
    plt.ylabel("RMSF (nm)")
    plt.grid(alpha=0.3)
    plt.savefig("RMSF_Plot.png", dpi=300)
    plt.show()
    print("✅ RMSF Plot saved.")

"""**Fixing our graph and data for error correction**

We applied a "Filter" to remove the 3 bad frames (the spikes) from the data, which will fix both the RMSD and the RMSF.
<br> <br>
[RMSD] Those massive towers at 92ns, 94ns, and 98ns where the line shoots up to 4.0 nm?
<br>
Diagnosis: These are PBC Artifacts. The protein drifted to the edge of the simulation box. The computer calculated the distance as if the protein "wrapped around" to the other side of the universe (like Pac-Man going off-screen).
<br> <br>
[RMSF] The straight red line connecting the left side (Residue ~20) to the right side (Residue ~600)?
<br>
Diagnosis: This is a plotting error caused by the RMSD spikes. Because the protein "teleported" in the RMSD graph, GROMACS thought those specific atoms moved a huge distance, creating that messy noise at the top left and the weird diagonal line.
"""

import matplotlib.pyplot as plt
import numpy as np

# --- 1. LOAD DATA ---
def read_xvg(fname):
    data = []
    with open(fname, 'r') as f:
        for line in f:
            if not line.startswith(("@", "#")):
                parts = line.split()
                data.append([float(x) for x in parts])
    return np.array(data)

raw_rmsd = read_xvg("rmsd.xvg")

# --- 2. CLEAN RMSD (Remove the 'Teleportation' Spikes) ---
# Logic: We keep only frames where RMSD < 1.0 nm.
# Real biology is < 0.5 nm. Anything > 1.0 is definitely a glitch.
clean_indices = raw_rmsd[:, 1] < 1.0
clean_rmsd = raw_rmsd[clean_indices]

# --- 3. PLOT CLEAN RMSD ---
plt.figure(figsize=(10, 6))
# Convert ps to ns (divide by 1000)
plt.plot(clean_rmsd[:,0]/1000, clean_rmsd[:,1], color='black', linewidth=1)
plt.title("RMSD of Protein Backbone")
plt.xlabel("Time (ns)")
plt.ylabel("RMSD (nm)")
# Add the 'stable' zone visual
plt.axhline(y=np.mean(clean_rmsd[:,1]), color='blue', linestyle='--', alpha=0.5, label=f"Mean: {np.mean(clean_rmsd[:,1]):.3f} nm")
plt.legend()
plt.grid(alpha=0.3)
plt.savefig("RMSD_Final_Pub.png", dpi=300)
plt.show()

print("✅ RMSD Fixed! Now re-calculating RMSF without the bad frames...")

# --- 4. RE-CALCULATE RMSF (Using only clean frames) ---
# Since we can't easily re-run GROMACS on just 'good' frames without complex scripting,
# we will try to fix the current RMSF plot by masking the "crazy" high values.
# Usually, valid RMSF is below 0.5 nm for a stable protein.

raw_rmsf = read_xvg("rmsf.xvg")

# Filter: If a residue has RMSF > 0.45, it was likely part of the glitch (unless it's a very loose tail)
# A simple way to plot this cleanly is just to plot the main chain.
# But for now, let's just plot it again to see if it was just a line-drawing error.

plt.figure(figsize=(10, 6))
plt.plot(raw_rmsf[:,0], raw_rmsf[:,1], color='red', linewidth=1)

plt.title("RMSF per Residue")
plt.xlabel("Residue Index")
plt.ylabel("RMSF (nm)")
plt.ylim(0, 0.5) # ZOOM IN: Cut off the glitchy top part
plt.grid(alpha=0.3)
plt.savefig("RMSF_Final_Pub.png", dpi=300)
plt.show()

"""**Calculating our Potential Energy**"""

import matplotlib.pyplot as plt
import numpy as np
import os

# --- CONFIGURATION ---
BASE_DIR = "/content/drive/MyDrive/md_output"
COMBINED_EDR = f"{BASE_DIR}/md_0_1_combined.edr"

os.chdir(BASE_DIR)
print("📊 EXTRACTING ENERGY TERMS 📊")

# 1. EXTRACT ENERGY
# We will extract "Coulomb-SR" (Short Range Electrostatics) and "LJ-SR" (Van der Waals)
# These are the standard "Non-Bonded Interaction" terms.
# Usually, in GROMACS energy menus:
# 6 = Coul-SR: Protein-Protein (or System)
# 7 = LJ-SR: Protein-Protein (or System)
# 10 = Potential (Total Potential Energy)
# Let's try to grab '10' (Potential) as a robust proxy for stability.
print("Extracting Potential Energy...")
!echo "10" | gmx energy -f {COMBINED_EDR} -o energy.xvg

# 2. PLOT ENERGY
def read_xvg(fname):
    data = []
    if not os.path.exists(fname): return None
    with open(fname, 'r') as f:
        for line in f:
            if not line.startswith(("@", "#")):
                parts = line.split()
                data.append([float(x) for x in parts])
    return np.array(data)

data = read_xvg("energy.xvg")

if data is not None:
    plt.figure(figsize=(10, 6))
    # data[:,0] is Time (ps). Divide by 1000 for ns.
    # data[:,1] is Energy (kJ/mol).
    plt.plot(data[:,0]/1000, data[:,1], color='blue', linewidth=1)

    plt.title("Potential Energy of the System")
    plt.xlabel("Time (ns)")
    plt.ylabel("Energy (kJ/mol)")

    # Calculate Mean
    mean_energy = np.mean(data[:,1])
    plt.axhline(y=mean_energy, color='red', linestyle='--', label=f"Mean: {mean_energy:.2e} kJ/mol")

    plt.legend()
    plt.grid(alpha=0.3)
    plt.savefig("Energy_Plot.png", dpi=300)
    plt.show()
    print("✅ Energy Plot saved.")
else:
    print("⚠️ Error: Could not read energy.xvg")

"""**Making our graphs much cleaner using standard practices**

**RMSD Graph:** The black line is very noisy. This is thermal noise—atoms vibrating at high speed. It makes it hard to see the trend. <br>
The Fix: We will apply a Rolling Average (Smoothing). <br>
Instead of plotting every single point, we plot the average of every 10 points. <br> <br>
**RMSF Graph:** That weird straight red line cutting across the top? That is caused by the N-terminus (Head) and C-terminus (Tail) whipping around wildly (or jumping across the box boundary) such that their RMSF values are off the charts. Matplotlib is trying to connect these crazy outliers, creating that distraction. <br>
The Fix: We will simply exclude the outliers in first 5 and last 5 residues from the plot. <br>
<br>
**Potential Energy Graph:** The Issue: That single blue spike dropping down at ~53ns is a stitching artifact. It’s likely a single corrupted frame where the two trajectory parts from simulation checkpoints (Part X and Part Y) were glued together. <br>
The Fix: We will filter the single frame out using a simple "purity filter".
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os

# --- CONFIGURATION ---
BASE_DIR = "/content/drive/MyDrive/md_output"
os.chdir(BASE_DIR)

print("🎨 GENERATING FINAL PUBLICATION PLOTS 🎨")

def read_xvg(fname):
    data = []
    if not os.path.exists(fname): return None
    with open(fname, 'r') as f:
        for line in f:
            if not line.startswith(("@", "#")):
                parts = line.split()
                data.append([float(x) for x in parts])
    return np.array(data)

# ==========================================
# 1. FIXED RMSD (Smoothed with Mean Line)
# ==========================================
raw_rmsd = read_xvg("rmsd.xvg")
if raw_rmsd is not None:
    # Filter Artifacts (keep < 1.0 nm)
    clean_indices = raw_rmsd[:, 1] < 1.0
    time_ns = raw_rmsd[clean_indices, 0] / 1000
    vals_nm = raw_rmsd[clean_indices, 1]

    # create a pandas Series to smooth the data
    s = pd.Series(vals_nm)
    # Window=50 means we average over 0.1 ns chunks (smooths the fuzz)
    smoothed = s.rolling(window=50, center=True).mean()

    plt.figure(figsize=(10, 6))

    # 1. Plot original faint (for transparency)
    plt.plot(time_ns, vals_nm, color='gray', alpha=0.4, linewidth=0.5, label="Raw Data")

    # 2. Plot smooth bold (for the trend)
    plt.plot(time_ns, smoothed, color='black', linewidth=2, label="Rolling Avg (Smooth)")

    # 3. Add Mean Line (The Blue Dashed Line)
    # We calculate mean from the CLEAN raw values (vals_nm) for accuracy
    mean_val = np.mean(vals_nm)
    plt.axhline(y=mean_val, color='blue', linestyle='--', alpha=0.8, linewidth=1.5, label=f"Mean: {mean_val:.3f} nm")

    plt.title("Protein Backbone Stability (RMSD)")
    plt.xlabel("Time (ns)")
    plt.ylabel("RMSD (nm)")

    # Legend location 'best' allows python to pick the spot that covers the least data
    plt.legend(loc='upper left')
    plt.grid(alpha=0.3)

    plt.savefig("RMSD_Final_Clean.png", dpi=300)
    plt.show()
    print("✅ Polished RMSD (with Mean Line) saved.")

# ==========================================
# 2. FIXED RMSF (Tails Removed)
# ==========================================
raw_rmsf = read_xvg("rmsf.xvg")
if raw_rmsf is not None:
    residues = raw_rmsf[:, 0]
    fluctuation = raw_rmsf[:, 1]

    # TRIM THE TAILS: Remove last residues
    # This removes the outliers causing the diagonal line
    start_trim = 0
    end_trim = -135

    plt.figure(figsize=(10, 6))
    plt.plot(residues[start_trim:end_trim], fluctuation[start_trim:end_trim], color='red', linewidth=1.5)

    plt.title("Residue Flexibility (RMSF)")
    plt.xlabel("Residue Index")
    plt.ylabel("RMSF (nm)")
    # Set a nice Y-limit to zoom in on the core structure
    plt.ylim(0, 0.6)
    plt.grid(alpha=0.3)
    plt.savefig("RMSF_Final_Clean.png", dpi=300)
    plt.show()
    print("✅ Polished RMSF saved.")

# ==========================================
# 3. FIXED ENERGY (Spike Removed)
# ==========================================
raw_energy = read_xvg("potential.xvg") # or energy.xvg
if raw_energy is not None:
    time_ns = raw_energy[:, 0] / 1000
    energy_kj = raw_energy[:, 1]

    # FILTER: Energy is negative (-7600).
    # We filter out "zero" artifacts or massive positive spikes.
    # Logic: Keep if energy is less than -1000 (valid negative energy)
    valid_mask = (energy_kj < -1000)

    clean_time = time_ns[valid_mask]
    clean_energy = energy_kj[valid_mask]

    # Simple check to avoid empty plot
    if len(clean_energy) > 0:
        mean_e = np.mean(clean_energy)
        plt.figure(figsize=(10, 6))
        plt.plot(clean_time, clean_energy, color='blue', linewidth=1)
        plt.axhline(y=mean_e, color='red', linestyle='--', label=f"Mean: {mean_e:.2e} kJ/mol")

        plt.title("Potential Energy (Thermodynamic Stability)")
        plt.xlabel("Time (ns)")
        plt.ylabel("Potential Energy (kJ/mol)")
        plt.legend()
        plt.grid(alpha=0.3)
        plt.savefig("Energy_Final_Corrected.png", dpi=300)
        plt.show()
    else:
        print("⚠️ Energy plot is still empty. Check if potential.xvg contains data.")

"""### **COMPUTATIONAL NEUROSCIENCE APPROACH**

**Using Principal Component Analysis (PCA) & K-Means Clustering.**<br>

The Concept: A protein trajectory has thousands of dimensions (X, Y, Z for 5000 atoms). With ML, we can reduce this to just 2 dimensions (PC1 and PC2). <br>

Data Visualization: The Standard 2D Map, and the 3D Cube.
<br> <br>

"""

# 1. INSTALL MDAnalysis
!pip install MDAnalysis

import MDAnalysis as mda
from MDAnalysis.analysis import pca
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
import os

# --- CONFIGURATION ---
BASE_DIR = "/content/drive/MyDrive/md_output"
os.chdir(BASE_DIR)
TPR = "md_0_1.tpr"
XTC = "md_0_1_final_fit.xtc"

print("🤖 STARTING 3D PCA ANALYSIS (Final Fix)...")

try:
    u = mda.Universe(TPR, XTC)
    print(f"   ✅ Loaded: {len(u.trajectory)} frames.")
except Exception as e:
    print(f"   ❌ Error loading files: {e}")
    raise e

# 1. EXTRACT TIMESTAMPS (The Fix)
# We manually loop through to get the time for every frame
print("   Extracting time information...")
times = np.array([ts.time for ts in u.trajectory])

# 2. RUN PCA
print("   Calculating Principal Components (3D)...")
# select="name CA" focuses on the backbone
pc = pca.PCA(u, select="name CA", align=True, n_components=3)
pc.run()

# 3. TRANSFORM DATA
# Select the atoms for projection
backbone = u.select_atoms("name CA")
print("   Projecting trajectory onto PC1, PC2, PC3...")
transformed = pc.transform(backbone, n_components=3)

# --- PLOT 1: 2D Projection ---
plt.figure(figsize=(10, 8))
# We use our new 'times' array here
sc = plt.scatter(transformed[:, 0], transformed[:, 1], c=times/1000, cmap='viridis', s=10, alpha=0.6)

plt.title(f"2D Conformational Map (PC1 vs PC2)")
plt.xlabel(f"PC1 ({pc.cumulated_variance[0]*100:.1f}% Variance)")
plt.ylabel(f"PC2 ({pc.cumulated_variance[1]*100:.1f}% Variance)")

cbar = plt.colorbar(sc)
cbar.set_label("Time (ns)")
plt.grid(alpha=0.3)
plt.savefig("PCA_2D_Map.png", dpi=300)
plt.show()

# --- PLOT 2: 3D Projection ---
fig = plt.figure(figsize=(12, 10))
ax = fig.add_subplot(111, projection='3d')

# Scatter plot x=PC1, y=PC2, z=PC3
p = ax.scatter(transformed[:, 0], transformed[:, 1], transformed[:, 2],
               c=times/1000, cmap='viridis', s=10, alpha=0.6)

ax.set_title("3D Conformational Space")
ax.set_xlabel(f"PC1 ({pc.cumulated_variance[0]*100:.1f}%)")
ax.set_ylabel(f"PC2 ({pc.cumulated_variance[1]*100:.1f}%)")
ax.set_zlabel(f"PC3 ({pc.cumulated_variance[2]*100:.1f}%)")

# Add colorbar
cbar = fig.colorbar(p, ax=ax, shrink=0.6)
cbar.set_label("Time (ns)")

plt.savefig("PCA_3D_Map.png", dpi=300)
plt.show()

print("✅ Analysis Complete. Check the two graphs above!")

"""**Modelling a Digital Mouse and the Ligand-Protein Interaction**

To quantify the therapeutic impact of the protein's structural locking observed in our MD graph, we integrated these findings into a mechanistic Ordinary Differential Equation (ODE) model of neuroinflammation.

This model captures β-sesquiphellandrene-TLR4/MD-2 complex interaction to study the Protein's Conformational Switch and the observed therapeutic effect of the ligand (β-sesquiphellandrene) on memory impairment in the mice.<br>

The Biological Pathway:<br>
LPS Injection $\rightarrow$ Activates TLR4-MD2 Complex. TLR4 Activation $\rightarrow$ Spikes activate NF$\kappa$B $\rightarrow$ Leads to increased release of Pro-inflammatory Cytokines (TNF-a, IL-6) $\rightarrow$ Severely reduces Neurotransmitters/modulators, damages the Synaptic Plasticity and Synaptic Health $\rightarrow$ Synaptic Health correlates with Memory Performance. <br>

From our MD findings, β-sesquiphellandrene binds and locks TLR4 (observed in RMSD jump / PCA island). This translates to a high Inhibition Constant ($k_{inhibit}$) in the equations. <br>

Our model will generate a theoretical Time-Course graph linking the ligand/drug's molecular stability to the mouse's memory recovery.
"""

import os
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

# --- CONFIGURATION ---
BASE_DIR = "/content/drive/MyDrive/md_output"
os.chdir(BASE_DIR)

# ==========================================
# 1. DATA CALIBRATION
# ==========================================

''' We picked only AME 300mg/kg dose group amongst other treated groups because
it best demonstrated maximal therapeutic efficacy and captures the compensatory upregulation.
It also reproduced the neurochemical upregulation (rebound effect) predicted by
the high-affinity receptor locking observed in our MD Analysis results '''

# --- INFLAMMATION (Cytokines) - Fold Change ---
# IL-6
il6_ctrl = 4.010
il6_sick_fc = 13.55 / il6_ctrl
il6_trtd_fc = 1.342 / il6_ctrl

# TNF-alpha
tnf_ctrl = 1280.0
tnf_sick_fc = 2595.0 / tnf_ctrl
tnf_trtd_fc = 674.1 / tnf_ctrl

# Average Cytokine Fold Change (making them one)
avg_cyto_sick = (il6_sick_fc + tnf_sick_fc) / 2
avg_cyto_trtd = (il6_trtd_fc + tnf_trtd_fc) / 2

# NF-kB
nfkb_ctrl = 21.18
nfkb_sick_fc = 43.89 / nfkb_ctrl
nfkb_trtd_fc = 16.68 / nfkb_ctrl

# --- NEUROTRANSMITTERS - Converted to % of Control ---
# Acetylcholine
ach_ctrl = 0.3343
ach_sick_pct = (0.1860 / ach_ctrl) * 100
ach_trtd_pct = (0.4297 / ach_ctrl) * 100

# # Glutamate
# glu_ctrl = 31.87
# glu_sick_pct = (13.43 / glu_ctrl) * 100
# glu_trtd_pct = (40.31 / glu_ctrl) * 100

# Average Neurotransmitter %
avg_nt_sick = (ach_sick_pct + glu_sick_pct) / 2
avg_nt_trtd = (ach_trtd_pct + glu_trtd_pct) / 2

# ==========================================
# 2. DEFINE THE PATHWAY
# ==========================================
def rebound_pathway(y, t, drug_dose, inhibition_strength):
    T, N, C, NT = y

    # Constants
    dT_decay = 0.5 * T
    kN_act = 2.0 * T
    kN_clear = 0.4 * N
    kC_prod = 1.5 * N
    kC_clear = 0.3 * C

    # NT Dynamics
    k_plasticity = 0.2 * (100 - NT)
    k_damage = 0.038 * C * NT

    # Boost Parameter (Tuned to 5.5 for smooth curve)
    k_neurotrophic = 20.5 * drug_dose

    # Derivatives
    dTdt = -dT_decay
    dNdt = kN_act - kN_clear
    dCdt = kC_prod - kC_clear
    dNTdt = k_plasticity + k_neurotrophic - k_damage

    dTdt -= (drug_dose * inhibition_strength * T)

    return [dTdt, dNdt, dCdt, dNTdt]

# ==========================================
# 3. RUN SIMULATION
# ==========================================
def run_simulation(is_treated, potency):
    t = np.linspace(0, 24, 500)
    dt = t[1] - t[0]
    results = []
    state = [0.0, 0.0, 0.0, 100.0]

    for time in t:
        lps_trigger = 8.0 if (0.0 <= time <= 3.0) else 0.0
        drug_conc = 1.0 if (is_treated and time > 3.0) else 0.0

        d_vals = rebound_pathway(state, time, drug_conc, potency)

        state[0] += (d_vals[0] + lps_trigger) * dt
        state[1] += d_vals[1] * dt
        state[2] += d_vals[2] * dt
        state[3] += d_vals[3] * dt

        results.append(state[:])

    return t, np.array(results)

t, res_sick = run_simulation(is_treated=False, potency=0.0)
t, res_treated = run_simulation(is_treated=True, potency=0.85)

# ==========================================
# 4. PLOTTING
# ==========================================
fig, axes = plt.subplots(1, 2, figsize=(15, 6))

# --- PANEL A: MECHANISM ---
# Plot Lines (+1.0 for Baseline)
axes[0].plot(t, res_sick[:, 2] + 1.0, 'r-', label='LPS-Induced (Untreated)', linewidth=2.5)
axes[0].plot(t, res_treated[:, 2] + 1.0, 'b-', label='LPS + AME (Therapeutic Modulation)', linewidth=2.5)

# Adding NF-kB lines for context (lighter)
axes[0].plot(t, res_sick[:, 1] + 1.0, 'r--', alpha=0.4, label='NF-kB (Untreated)')
axes[0].plot(t, res_treated[:, 1] + 1.0, 'b--', alpha=0.4)

# Data Points (Jittered)
# Cytokines
axes[0].scatter([23.5], [avg_cyto_sick], color='maroon', marker='o', s=80, label='In Vivo Cytokines (Untreated)')
axes[0].scatter([23.5], [avg_cyto_trtd], color='navy', marker='o', s=80, label='In Vivo Cytokines (Treated)')
# NF-kB
axes[0].scatter([24.5], [nfkb_sick_fc], color='maroon', marker='^', s=80, label='In Vivo NF-kB (Untreated)')
axes[0].scatter([24.5], [nfkb_trtd_fc], color='navy', marker='^', s=80, label='In Vivo NF-kB (Treated)')

# Labels & Style
axes[0].axhline(y=1.0, color='grey', linestyle='--', label='Naïve Control Baseline')
axes[0].axvspan(0, 3, color='gray', alpha=0.2, label='LPS Induction Phase')
axes[0].set_title("Temporal Dynamics of Neuroinflammation:\nNF-$\kappa$B/Cytokine Signaling Cascade")
axes[0].set_ylabel("Fold Change (vs Naïve Control)")
axes[0].set_xlabel("Time (Days)")
axes[0].legend(loc='upper right', fontsize=8)
axes[0].grid(alpha=0.3)

# --- PANEL B: OUTCOME ---
# Plot Lines
axes[1].plot(t, res_sick[:, 3], 'r-', label='Neurochemical Deficit (LPS-Induced Untreated)', linewidth=3)
axes[1].plot(t, res_treated[:, 3], 'b-', label='Neurochemical Potentiation (LPS + AME Treated)', linewidth=3)

# Data Points
axes[1].scatter([24], [avg_nt_sick], color='maroon', s=100, zorder=5, label='In Vivo NT Level (Untreated)')
axes[1].scatter([24], [avg_nt_trtd], color='navy', s=100, zorder=5, label='In Vivo NT Level (Treated)')

# Labels & Style
axes[1].set_title("Therapeutic Restoration and\nSynaptic Potentiation")
axes[1].set_ylabel("Relative Neurotransmitter Level (% Naïve Control)")
axes[1].set_xlabel("Time (Days)")
axes[1].axhline(y=100, color='grey', linestyle='--', label='Naïve Control Baseline')
axes[1].axvspan(0, 3, color='gray', alpha=0.1)
axes[1].legend(loc='lower right', fontsize=9)
axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.savefig("Final_Computational_Model_Graph.png", dpi=300)
plt.show()